### ISSUE TITLE
Let validation files take a schema path for the schema value

### ISSUE THREAD

**Issue by tstirrat15** [authzed/zed#453]
Currently you have to concatenate the schema file into the validation file if you want to maintain them separately. If a validation file can reference a schema file by path, you can have the validation file(s) live near the schema and run them fairly easily.

It might be a little funky because the current value for this key is also a string - i'll need to figure out what the validation looks like - but it seems doable.

```
schema: myschema.zed
relationships: ...
assertions:
  assertTrue: []
  assertFalse: []
validation: ...
```
