### ISSUE TITLE
Add golanglint-ci to Build Workflow

### ISSUE THREAD

**Issue by jzelinskie** [authzed/zed#65]
We're using revive right now for linting in the build workflow, but it's also not configured to fail if anything is wrong.

Here's the config we use in SpiceDB:
```yaml
      - uses: "golangci/golangci-lint-action@v2"
        with:
          version: "v1.42"
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: false
```
